Updated colourmapper to map colour in the new way for Grafana
apel/grafana-dashboards pull request #175
Opened 2024-05-01 09:54 UTC by Will-Cross1

Updated so that fieldConfig is used in the json file instead of using panels

Resolves #131

2024-05-02 13:34 UTC, tofu-rocketry requested changes

2024-05-02 13:34 UTC, tofu-rocketry commented on scripts/colourmapper.py
> +    return {
Could we get a docstring that describes what this function does?

2024-05-02 13:34 UTC, tofu-rocketry commented on scripts/colourmapper.py
>              data['panels'][i]['aliasColors'] = alias_colors
So this will set the colours using both methods for each panel, right? (That's fine, just want to check.)

Could do with a comment explaining that and the two different styles of config setting.

2024-05-02 14:11 UTC, Will-Cross1 commented on scripts/colourmapper.py
> +    return {
Added a description in next commit

2024-05-02 14:11 UTC, Will-Cross1 commented on scripts/colourmapper.py
>              data['panels'][i]['aliasColors'] = alias_colors
Added a comment in next commit

2024-05-02 14:37 UTC, tofu-rocketry commented on scripts/colourmapper.py
> +            except KeyError:
Is this needed due to 'fieldConfig' not being used for each panel?

2024-05-02 14:55 UTC, Will-Cross1 commented on scripts/colourmapper.py
> +            except KeyError:
Yes there was an instance of it not existing causing it to fail

2024-05-08 08:22 UTC, tofu-rocketry approved these changes

2024-05-08 09:21 UTC, merged