Copied accelerator accounting to InterTwin
apel/grafana-dashboards pull request #184
Opened 2024-09-04 14:19 UTC by Will-Cross1

Resolves GT-538

Copied accelerator_accounting.json to the InterTwin directory

Changed iris_accelerator to intertwin_accelerator

Added the new file to the intertwin.yml file

2024-09-05 10:31 UTC, gregcorbett commented
The change itself looks good to me. I have a couple of nitpicks about the commit message:

- 'Copyed' -> 'Copied'
- 'Copyed accelerator_accounting.json to the InterTwin directory': copied from where? It looks like the file just appears in the Git repo?
- 'Changed iris_accelerator to intertwin_accelerator': It's not clear to me what this refer to?

2024-09-05 10:40 UTC, tofu-rocketry requested changes

2024-09-05 10:40 UTC, tofu-rocketry commented on provisioning/dashboards/intertwin.yml
> +- name: InterTwin Accelerator Dashboard
Could you fix the capitalisation in this and line 4 to use "interTwin"?

2024-09-05 10:40 UTC, tofu-rocketry commented on dashboards/intertwin/accelerator_accounting.json
> +}
Add a newline at the end so that it follows the Unix standard.

2024-09-05 11:29 UTC, Will-Cross1 commented on provisioning/dashboards/intertwin.yml
> +- name: InterTwin Accelerator Dashboard
Should I change the other provider inside also?

2024-09-05 13:13 UTC, gregcorbett approved these changes
LGTM, you might want to squash the two commits once Adrian has reviewed as well.

2024-09-10 07:57 UTC, Will-Cross1 commented on dashboards/intertwin/accelerator_accounting.json
> +}
resolved in latest commit

2024-09-10 09:10 UTC, tofu-rocketry approved these changes

2024-09-10 09:10 UTC, merged